services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/squadjokes
    depends_on:
      - db
    volumes:
      - .:/opt/app
    command: yarn dev

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=squadjokes
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
