services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/squadjokes
      - SECRET_KEY=f2d0078191f67940255cff2e5e500ab8e8f9e6ae2d0cdbd813a3ef4368804078
      - GOOGLE_CLIENT_ID=your-google-client-id.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=your-google-client-secret
      - NOTIFIER_METHOD=email
    depends_on:
      - db
    volumes:
      - .:/opt/app
    command: yarn dev

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=squadjokes
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
