openapi: 3.0.3
info:
  title: Squad Jokes API
  version: 1.0.0
  description: REST API for fetching, saving, updating, and deleting jokes, as well as basic math operations, notifications, and authentication.
servers:
  - url: http://localhost:8000
paths:
  /jokes:
    get:
      summary: Get a random joke from an external API
      parameters:
        - in: query
          name: source
          schema:
            type: string
            enum: [chuck, dad]
          description: Source of the joke (chuck or dad). If omitted, random.
      responses:
        "200":
          description: Joke fetched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  joke:
                    type: string
                  from:
                    type: string
        "422":
          description: Invalid source or error fetching joke
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    post:
      summary: Save a new joke to the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                joke:
                  type: string
              required: [joke]
      responses:
        "201":
          description: Joke saved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    text:
                      type: string
        "422":
          description: Joke text missing or error saving
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /jokes/emparejados:
    get:
      summary: Get 5 paired Chuck Norris and Dad jokes
      description: Fetches 5 jokes from each external API in parallel, pairs them, and returns a creative combination.
      responses:
        "200":
          description: Array of paired jokes
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    chuck:
                      type: string
                      description: Chuck Norris joke
                    dad:
                      type: string
                      description: Dad joke
                    combinado:
                      type: string
                      description: Creative combination of both jokes
        "422":
          description: Error fetching jokes from external APIs
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /jokes/{id}:
    put:
      summary: Update a joke by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                joke:
                  type: string
              required: [joke]
      responses:
        "200":
          description: Joke updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "404":
          description: Joke not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    delete:
      summary: Delete a joke by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Joke deleted successfully
        "404":
          description: Joke not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /math/lcm:
    get:
      summary: Calculate the Least Common Multiple (LCM) of numbers
      parameters:
        - in: query
          name: numbers
          required: true
          schema:
            type: string
          description: Comma-separated list of integers (e.g., 2,3,5)
      responses:
        "200":
          description: LCM calculated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  lcm:
                    type: integer
        "422":
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /math/increment:
    get:
      summary: Increment a number by 1
      parameters:
        - in: query
          name: number
          required: true
          schema:
            type: string
          description: Integer to increment
      responses:
        "200":
          description: Number incremented successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: integer
        "422":
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /notifications:
    post:
      summary: Send a notification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                recipient:
                  type: string
                message:
                  type: string
              required: [recipient, message]
      responses:
        "200":
          description: Notification sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        "400":
          description: Missing recipient or message
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /auth/login:
    post:
      summary: Login with email and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required: [email, password]
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        "400":
          description: Missing email or password
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "401":
          description: Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /api/usuario:
    get:
      summary: Access user-protected route
      security:
        - bearerAuth: []
      responses:
        "200":
          description: User access granted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    type: object
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /api/admin:
    get:
      summary: Access admin-protected route
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Admin access granted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    type: object
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /oauth/external/google:
    get:
      summary: Start Google OAuth2 login
      responses:
        "302":
          description: Redirect to Google login
  /oauth/external/google/redirect:
    get:
      summary: Google OAuth2 callback
      responses:
        "302":
          description: Redirect to external callback
  /auth/external/callback:
    get:
      summary: Handle external login callback
      parameters:
        - in: query
          name: profile
          required: true
          schema:
            type: string
      responses:
        "200":
          description: External login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        "400":
          description: Missing profile
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "404":
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
